package databaseModel;
// Generated 06-jun-2018 11:37:45 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdministradoresId generated by hbm2java
 */
@Embeddable
public class AdministradoresId implements java.io.Serializable {

	private String adminCodigo;
	private String adminNombre;
	private String adminApellidos;
	private String adminEdad;
	private String adminTelefono;
	private String adminDni;

	public AdministradoresId() {
	}

	public AdministradoresId(String adminCodigo, String adminNombre, String adminApellidos, String adminEdad,
			String adminTelefono, String adminDni) {
		this.adminCodigo = adminCodigo;
		this.adminNombre = adminNombre;
		this.adminApellidos = adminApellidos;
		this.adminEdad = adminEdad;
		this.adminTelefono = adminTelefono;
		this.adminDni = adminDni;
	}

	@Column(name = "Admin_Codigo", nullable = false, length = 10)
	public String getAdminCodigo() {
		return this.adminCodigo;
	}

	public void setAdminCodigo(String adminCodigo) {
		this.adminCodigo = adminCodigo;
	}

	@Column(name = "Admin_Nombre", nullable = false, length = 10)
	public String getAdminNombre() {
		return this.adminNombre;
	}

	public void setAdminNombre(String adminNombre) {
		this.adminNombre = adminNombre;
	}

	@Column(name = "Admin_Apellidos", nullable = false, length = 10)
	public String getAdminApellidos() {
		return this.adminApellidos;
	}

	public void setAdminApellidos(String adminApellidos) {
		this.adminApellidos = adminApellidos;
	}

	@Column(name = "Admin_Edad", nullable = false, length = 2)
	public String getAdminEdad() {
		return this.adminEdad;
	}

	public void setAdminEdad(String adminEdad) {
		this.adminEdad = adminEdad;
	}

	@Column(name = "Admin_Telefono", nullable = false, length = 9)
	public String getAdminTelefono() {
		return this.adminTelefono;
	}

	public void setAdminTelefono(String adminTelefono) {
		this.adminTelefono = adminTelefono;
	}

	@Column(name = "Admin_DNI", nullable = false, length = 9)
	public String getAdminDni() {
		return this.adminDni;
	}

	public void setAdminDni(String adminDni) {
		this.adminDni = adminDni;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdministradoresId))
			return false;
		AdministradoresId castOther = (AdministradoresId) other;

		return ((this.getAdminCodigo() == castOther.getAdminCodigo()) || (this.getAdminCodigo() != null
				&& castOther.getAdminCodigo() != null && this.getAdminCodigo().equals(castOther.getAdminCodigo())))
				&& ((this.getAdminNombre() == castOther.getAdminNombre())
						|| (this.getAdminNombre() != null && castOther.getAdminNombre() != null
								&& this.getAdminNombre().equals(castOther.getAdminNombre())))
				&& ((this.getAdminApellidos() == castOther.getAdminApellidos())
						|| (this.getAdminApellidos() != null && castOther.getAdminApellidos() != null
								&& this.getAdminApellidos().equals(castOther.getAdminApellidos())))
				&& ((this.getAdminEdad() == castOther.getAdminEdad()) || (this.getAdminEdad() != null
						&& castOther.getAdminEdad() != null && this.getAdminEdad().equals(castOther.getAdminEdad())))
				&& ((this.getAdminTelefono() == castOther.getAdminTelefono())
						|| (this.getAdminTelefono() != null && castOther.getAdminTelefono() != null
								&& this.getAdminTelefono().equals(castOther.getAdminTelefono())))
				&& ((this.getAdminDni() == castOther.getAdminDni()) || (this.getAdminDni() != null
						&& castOther.getAdminDni() != null && this.getAdminDni().equals(castOther.getAdminDni())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAdminCodigo() == null ? 0 : this.getAdminCodigo().hashCode());
		result = 37 * result + (getAdminNombre() == null ? 0 : this.getAdminNombre().hashCode());
		result = 37 * result + (getAdminApellidos() == null ? 0 : this.getAdminApellidos().hashCode());
		result = 37 * result + (getAdminEdad() == null ? 0 : this.getAdminEdad().hashCode());
		result = 37 * result + (getAdminTelefono() == null ? 0 : this.getAdminTelefono().hashCode());
		result = 37 * result + (getAdminDni() == null ? 0 : this.getAdminDni().hashCode());
		return result;
	}

}
