package databaseModel;
// Generated 06-jun-2018 11:37:45 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Administradores generated by hbm2java
 */
@Entity
@Table(name = "administradores", catalog = "colegio")
public class Administradores implements java.io.Serializable {

	private AdministradoresId id;

	public Administradores() {
	}

	public Administradores(AdministradoresId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "adminCodigo", column = @Column(name = "Admin_Codigo", nullable = false, length = 10)),
			@AttributeOverride(name = "adminNombre", column = @Column(name = "Admin_Nombre", nullable = false, length = 10)),
			@AttributeOverride(name = "adminApellidos", column = @Column(name = "Admin_Apellidos", nullable = false, length = 10)),
			@AttributeOverride(name = "adminEdad", column = @Column(name = "Admin_Edad", nullable = false, length = 2)),
			@AttributeOverride(name = "adminTelefono", column = @Column(name = "Admin_Telefono", nullable = false, length = 9)),
			@AttributeOverride(name = "adminDni", column = @Column(name = "Admin_DNI", nullable = false, length = 9)) })
	public AdministradoresId getId() {
		return this.id;
	}

	public void setId(AdministradoresId id) {
		this.id = id;
	}

}
