package databaseModel;
// Generated 06-jun-2018 11:37:45 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name = "alumnos", catalog = "colegio")
public class Alumnos implements java.io.Serializable {

	private String alumCodigo;
	private String alumNombre;
	private String alumApellidos;
	private String alumEdad;
	private String alumTelefono;
	private String alumDni;
	private String alumCurso;

	public Alumnos() {
	}

	public Alumnos(String alumCodigo, String alumNombre, String alumApellidos, String alumEdad, String alumTelefono,
			String alumDni, String alumCurso) {
		this.alumCodigo = alumCodigo;
		this.alumNombre = alumNombre;
		this.alumApellidos = alumApellidos;
		this.alumEdad = alumEdad;
		this.alumTelefono = alumTelefono;
		this.alumDni = alumDni;
		this.alumCurso = alumCurso;
	}

	@Id

	@Column(name = "Alum_Codigo", unique = true, nullable = false, length = 10)
	public String getAlumCodigo() {
		return this.alumCodigo;
	}

	public void setAlumCodigo(String alumCodigo) {
		this.alumCodigo = alumCodigo;
	}

	@Column(name = "Alum_Nombre", nullable = false, length = 10)
	public String getAlumNombre() {
		return this.alumNombre;
	}

	public void setAlumNombre(String alumNombre) {
		this.alumNombre = alumNombre;
	}

	@Column(name = "Alum_Apellidos", nullable = false, length = 10)
	public String getAlumApellidos() {
		return this.alumApellidos;
	}

	public void setAlumApellidos(String alumApellidos) {
		this.alumApellidos = alumApellidos;
	}

	@Column(name = "Alum_Edad", nullable = false, length = 2)
	public String getAlumEdad() {
		return this.alumEdad;
	}

	public void setAlumEdad(String alumEdad) {
		this.alumEdad = alumEdad;
	}

	@Column(name = "Alum_Telefono", nullable = false, length = 10)
	public String getAlumTelefono() {
		return this.alumTelefono;
	}

	public void setAlumTelefono(String alumTelefono) {
		this.alumTelefono = alumTelefono;
	}

	@Column(name = "Alum_DNI", nullable = false, length = 10)
	public String getAlumDni() {
		return this.alumDni;
	}

	public void setAlumDni(String alumDni) {
		this.alumDni = alumDni;
	}

	@Column(name = "Alum_Curso", nullable = false, length = 10)
	public String getAlumCurso() {
		return this.alumCurso;
	}

	public void setAlumCurso(String alumCurso) {
		this.alumCurso = alumCurso;
	}

}
