package databaseModel;
// Generated 06-jun-2018 11:37:45 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Notas generated by hbm2java
 */
@Entity
@Table(name = "notas", catalog = "colegio")
public class Notas implements java.io.Serializable {

	private String notaCodigo;
	private String notaAlumCodigo;
	private String notaAsigCodigo;
	private String notaProfCodigo;
	private String notaTrim1;
	private String notaTrim2;
	private String notaTrim3;
	private String notaCalif;

	public Notas() {
	}

	public Notas(String notaCodigo, String notaAlumCodigo, String notaAsigCodigo, String notaProfCodigo,
			String notaTrim1, String notaTrim2, String notaTrim3, String notaCalif) {
		this.notaCodigo = notaCodigo;
		this.notaAlumCodigo = notaAlumCodigo;
		this.notaAsigCodigo = notaAsigCodigo;
		this.notaProfCodigo = notaProfCodigo;
		this.notaTrim1 = notaTrim1;
		this.notaTrim2 = notaTrim2;
		this.notaTrim3 = notaTrim3;
		this.notaCalif = notaCalif;
	}

	@Id

	@Column(name = "Nota_Codigo", unique = true, nullable = false, length = 10)
	public String getNotaCodigo() {
		return this.notaCodigo;
	}

	public void setNotaCodigo(String notaCodigo) {
		this.notaCodigo = notaCodigo;
	}

	@Column(name = "Nota_Alum_Codigo", nullable = false, length = 10)
	public String getNotaAlumCodigo() {
		return this.notaAlumCodigo;
	}

	public void setNotaAlumCodigo(String notaAlumCodigo) {
		this.notaAlumCodigo = notaAlumCodigo;
	}

	@Column(name = "Nota_Asig_Codigo", nullable = false, length = 10)
	public String getNotaAsigCodigo() {
		return this.notaAsigCodigo;
	}

	public void setNotaAsigCodigo(String notaAsigCodigo) {
		this.notaAsigCodigo = notaAsigCodigo;
	}

	@Column(name = "Nota_Prof_Codigo", nullable = false, length = 10)
	public String getNotaProfCodigo() {
		return this.notaProfCodigo;
	}

	public void setNotaProfCodigo(String notaProfCodigo) {
		this.notaProfCodigo = notaProfCodigo;
	}

	@Column(name = "Nota_Trim1", nullable = false, length = 3)
	public String getNotaTrim1() {
		return this.notaTrim1;
	}

	public void setNotaTrim1(String notaTrim1) {
		this.notaTrim1 = notaTrim1;
	}

	@Column(name = "Nota_Trim2", nullable = false, length = 3)
	public String getNotaTrim2() {
		return this.notaTrim2;
	}

	public void setNotaTrim2(String notaTrim2) {
		this.notaTrim2 = notaTrim2;
	}

	@Column(name = "Nota_Trim3", nullable = false, length = 3)
	public String getNotaTrim3() {
		return this.notaTrim3;
	}

	public void setNotaTrim3(String notaTrim3) {
		this.notaTrim3 = notaTrim3;
	}

	@Column(name = "Nota_Calif", nullable = false, length = 3)
	public String getNotaCalif() {
		return this.notaCalif;
	}

	public void setNotaCalif(String notaCalif) {
		this.notaCalif = notaCalif;
	}

}
