package databaseModel;
// Generated 06-jun-2018 11:37:45 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profesores generated by hbm2java
 */
@Entity
@Table(name = "profesores", catalog = "colegio")
public class Profesores implements java.io.Serializable {

	private String profCodigo;
	private String profNombre;
	private String profApellidos;
	private String profEdad;
	private String profTelefono;
	private String profDni;
	private String profCurso;

	public Profesores() {
	}

	public Profesores(String profCodigo, String profNombre, String profApellidos, String profEdad, String profTelefono,
			String profDni, String profCurso) {
		this.profCodigo = profCodigo;
		this.profNombre = profNombre;
		this.profApellidos = profApellidos;
		this.profEdad = profEdad;
		this.profTelefono = profTelefono;
		this.profDni = profDni;
		this.profCurso = profCurso;
	}

	@Id

	@Column(name = "Prof_Codigo", unique = true, nullable = false, length = 10)
	public String getProfCodigo() {
		return this.profCodigo;
	}

	public void setProfCodigo(String profCodigo) {
		this.profCodigo = profCodigo;
	}

	@Column(name = "Prof_Nombre", nullable = false, length = 10)
	public String getProfNombre() {
		return this.profNombre;
	}

	public void setProfNombre(String profNombre) {
		this.profNombre = profNombre;
	}

	@Column(name = "Prof_Apellidos", nullable = false, length = 10)
	public String getProfApellidos() {
		return this.profApellidos;
	}

	public void setProfApellidos(String profApellidos) {
		this.profApellidos = profApellidos;
	}

	@Column(name = "Prof_Edad", nullable = false, length = 2)
	public String getProfEdad() {
		return this.profEdad;
	}

	public void setProfEdad(String profEdad) {
		this.profEdad = profEdad;
	}

	@Column(name = "Prof_Telefono", nullable = false, length = 9)
	public String getProfTelefono() {
		return this.profTelefono;
	}

	public void setProfTelefono(String profTelefono) {
		this.profTelefono = profTelefono;
	}

	@Column(name = "Prof_DNI", nullable = false, length = 9)
	public String getProfDni() {
		return this.profDni;
	}

	public void setProfDni(String profDni) {
		this.profDni = profDni;
	}

	@Column(name = "Prof_Curso", nullable = false, length = 10)
	public String getProfCurso() {
		return this.profCurso;
	}

	public void setProfCurso(String profCurso) {
		this.profCurso = profCurso;
	}

}
