package databaseModel;
// Generated 06-jun-2018 11:37:45 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "colegio")
public class Usuarios implements java.io.Serializable {

	private String usuarioCod;
	private String usuarioPass;
	private String usuarioTipo;

	public Usuarios() {
	}

	public Usuarios(String usuarioCod, String usuarioPass, String usuarioTipo) {
		this.usuarioCod = usuarioCod;
		this.usuarioPass = usuarioPass;
		this.usuarioTipo = usuarioTipo;
	}

	@Id

	@Column(name = "Usuario_Cod", unique = true, nullable = false, length = 10)
	public String getUsuarioCod() {
		return this.usuarioCod;
	}

	public void setUsuarioCod(String usuarioCod) {
		this.usuarioCod = usuarioCod;
	}

	@Column(name = "Usuario_pass", nullable = false, length = 10)
	public String getUsuarioPass() {
		return this.usuarioPass;
	}

	public void setUsuarioPass(String usuarioPass) {
		this.usuarioPass = usuarioPass;
	}

	@Column(name = "Usuario_tipo", nullable = false, length = 13)
	public String getUsuarioTipo() {
		return this.usuarioTipo;
	}

	public void setUsuarioTipo(String usuarioTipo) {
		this.usuarioTipo = usuarioTipo;
	}

}
